### ISSUE TITLE
Can't Upgrade to 1.3.1 from irl's PPA on Ubuntu 14.04

### ISSUE THREAD

**Issue by the-solipsist** [TheTorProject/ooni-probe#434] opened 2015-11-24 01:21 UTC
I'm on Ubuntu 14.04, and ooniprobe won't upgrade from 1.2.2 to 1.3.1:

```
$ sudo apt-get upgrade
Reading package lists...
Building dependency tree...
Reading state information...
The following packages have been kept back:
  ooniprobe
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

```
$ apt-cache policy ooniprobe
ooniprobe:
  Installed: 1.2.2-1ppa1
  Candidate: 1.3.1-1ppa1
  Version table:
     1.3.1-1ppa1 0
        500 http://ppa.launchpad.net/irl/ooni/ubuntu/ trusty/main amd64 Packages
 *** 1.2.2-1ppa1 0
        100 /var/lib/dpkg/status
```

```
$ apt-cache showpkg ooniprobe
Package: ooniprobe
Versions: 
1.3.1-1ppa1 (/var/lib/apt/lists/ppa.launchpad.net_irl_ooni_ubuntu_dists_trusty_main_binary-amd64_Packages)
 Description Language: 
                 File: /var/lib/apt/lists/ppa.launchpad.net_irl_ooni_ubuntu_dists_trusty_main_binary-amd64_Packages
                  MD5: 58b9177aa0664c0dea0c81f15554e98b
 Description Language: en
                 File: /var/lib/apt/lists/ppa.launchpad.net_irl_ooni_ubuntu_dists_trusty_main_i18n_Translation-en
                  MD5: 58b9177aa0664c0dea0c81f15554e98b

1.2.2-1ppa1 (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/ppa.launchpad.net_irl_ooni_ubuntu_dists_trusty_main_binary-amd64_Packages
                  MD5: 58b9177aa0664c0dea0c81f15554e98b
 Description Language: en
                 File: /var/lib/apt/lists/ppa.launchpad.net_irl_ooni_ubuntu_dists_trusty_main_i18n_Translation-en
                  MD5: 58b9177aa0664c0dea0c81f15554e98b


Reverse Depends: 
Dependencies: 
1.3.1-1ppa1 - debconf (18 0.5) debconf-2.0 (0 (null)) python (0 (null)) python-characteristic (0 (null)) python-cryptography (0 (null)) python-geoip (0 (null)) python-ipaddr (0 (null)) python-openssl (0 (null)) python-parsley (0 (null)) python-pyasn1 (0 (null)) python-scapy (0 (null)) python-twisted (0 (null)) python-txsocksx (0 (null)) python-txtorcon (0 (null)) python-yaml (0 (null)) python-zope.interface (0 (null)) python:any (3 2.8) python:any (2 2.7.5-5~) adduser (0 (null)) tor (0 (null)) geoip-database (0 (null)) geoip-database-contrib (0 (null)) obfsproxy (0 (null)) python-dumbnet (0 (null)) python-pypcap (0 (null)) 
1.2.2-1ppa1 - python (2 2.7) python (3 2.8) python:any (2 2.7.1-0ubuntu2) python-yaml (0 (null)) python-twisted (0 (null)) python-ipaddr (0 (null)) python-openssl (0 (null)) python-geoip (0 (null)) python-txtorcon (0 (null)) python-txsocksx (0 (null)) python-parsley (0 (null)) python-scapy (0 (null)) python-pypcap (0 (null)) tor (0 (null)) geoip-database (0 (null)) geoip-database-contrib (0 (null)) obfsproxy (0 (null)) python-dumbnet (0 (null)) 
Provides: 
1.3.1-1ppa1 - 
1.2.2-1ppa1 - 
Reverse Provides: 
```

Happy to provide any other information as needed.

**Comment by anadahz** [comment] 2015-11-26 01:57
@the-solipsist have you tried using aptitude?
It 'll provide more info as to which packages need to be removed/installed on your current setup.

**Comment by hellais** [comment] 2016-06-09 09:53
Is this still relevant can we consider this closed? cc @irl

**Comment by irl** [comment] 2016-06-09 09:55
Currently I'm blocking this on https://trac.torproject.org/projects/tor/ticket/19275, but I guess really it doesn't have to. It's not fixed, but I'll move it up to today's todo.

**Comment by irl** [comment] 2016-06-09 09:57
@hellais: This is a duplicate of #460 so this can actually be closed. Please assign #460 to me.

**Comment by hellais** [comment] 2016-06-09 10:08
Ok closing as #460 superseeds this issue.

**Closed by hellais** 2016-06-09 10:08 UTC
