### ISSUE TITLE
Web connectivity test input without http(s):// prefix

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#640] opened 2016-10-17 01:18 UTC
Web connectivity test URL option should either append `http://` if no `http(s)://` is being supplied 
or inform the user that the test is not going to run as expected since a given input (URL) must include the http(s):// prefix.

**Comment by hellais** [comment] 2016-10-17 07:57
duplicate of #639. closing.

**Closed by hellais** 2016-10-17 07:57 UTC
Labels: duplicate
