### ISSUE TITLE
ooniprobe unmet dependencies in Ubuntu 14.04.1 LTS

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#544] opened 2016-06-16 00:17 UTC
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.1 LTS
Release:        14.04
Codename:       trusty

----------------------------------
`# add-apt-repository ppa:irl/ooni`
```
 A free software, global observation network for detecting censorship, surveillance and traffic manipulation on the internet.

https://ooni.torproject.org/
 More info: https://launchpad.net/~irl/+archive/ubuntu/ooni
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keyring `/tmp/tmpagetq0t0/secring.gpg' created
gpg: keyring `/tmp/tmpagetq0t0/pubring.gpg' created
gpg: requesting key 87728E9B from hkp server keyserver.ubuntu.com
gpg: /tmp/tmpagetq0t0/trustdb.gpg: trustdb created
gpg: key 87728E9B: public key "Launchpad PPA for Iain R. Learmonth" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
OK
```
`# apt-get update && apt-get install ooniprobe`
```
Ign http://nl.archive.ubuntu.com trusty InRelease
Hit http://nl.archive.ubuntu.com trusty Release.gpg
Hit http://nl.archive.ubuntu.com trusty Release
Get:1 http://ppa.launchpad.net trusty InRelease [16.0 kB]
Hit http://nl.archive.ubuntu.com trusty/main amd64 Packages
Hit http://nl.archive.ubuntu.com trusty/main Translation-en
Ign http://nl.archive.ubuntu.com trusty/main Translation-en_US
Get:2 http://ppa.launchpad.net trusty/main amd64 Packages [1,758 B]
Hit http://security.ubuntu.com trusty-updates InRelease
Get:3 http://ppa.launchpad.net trusty/main Translation-en [1,834 B]
Hit http://security.ubuntu.com trusty-updates/main amd64 Packages
Hit http://security.ubuntu.com trusty-updates/main Translation-en
Fetched 19.5 kB in 0s (49.9 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ooniprobe : Depends: python-txtorcon but it is not going to be installed
             Depends: python-txsocksx but it is not installable
             Depends: python-scapy but it is not installable
             Recommends: python-dumbnet but it is not installable
             Recommends: python-pypcap but it is not installable
E: Unable to correct problems, you have held broken packages.
```
cc @irl

**Comment by irl** [comment] 2016-06-16 08:08
I guess futher backports are required ):

To avoid this happening in future, I am going to be running piuparts in a jenkins job on the packages. This will identify problems such as this.

Will investigate which packages are still missing and which are just not installable due to dependencies.

**Comment by irl** [comment] 2016-06-19 16:17
Tested the following and cannot reproduce any issues:

```
root@ubuntu:/# cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04 LTS"
root@ubuntu:/# echo "deb http://deb.torproject.org/torproject.org trusty main" >> /etc/apt/sources.list
root@ubuntu:/# gpg --keyserver keys.gnupg.net --recv 886DDD89
[...]
root@ubuntu:/# gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
OK
root@ubuntu:/# apt update
Ign http://gb.archive.ubuntu.com trusty InRelease
Hit http://gb.archive.ubuntu.com trusty Release.gpg
Hit http://gb.archive.ubuntu.com trusty Release
Hit http://gb.archive.ubuntu.com trusty/main amd64 Packages  
Hit http://gb.archive.ubuntu.com trusty/universe amd64 Packages
Hit http://gb.archive.ubuntu.com trusty/multiverse amd64 Packages           
Hit http://gb.archive.ubuntu.com trusty/restricted amd64 Packages           
Get:1 http://deb.torproject.org trusty InRelease [3509 B]                   
Get:2 http://deb.torproject.org trusty/main Sources [2668 B]
Get:3 http://deb.torproject.org trusty/main amd64 Packages [3662 B]
Fetched 9839 B in 0s (33.3 kB/s)
Reading package lists... Done
root@ubuntu:/# apt install ooniprobe
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  geoip-database libevent-2.0-5 libexpat1 libffi6 libgeoip1 libpython-stdlib
  libpython2.7-minimal libpython2.7-stdlib libseccomp2 libssl1.0.0 libyaml-0-2
  mime-support python python-crypto python-geoip python-ipaddr python-minimal
  python-openssl python-parsley python-pkg-resources python-pyasn1
  python-scapy python-twisted python-twisted-bin python-twisted-conch
  python-twisted-core python-twisted-lore python-twisted-mail
  python-twisted-names python-twisted-news python-twisted-runner
  python-twisted-web python-twisted-words python-txsocksx python-txtorcon
  python-yaml python-zope.interface python2.7 python2.7-minimal tor
Suggested packages:
  geoip-bin geoip-database-contrib obfsproxy python-doc python-tk
  python-crypto-dbg python-crypto-doc python-openssl-doc python-openssl-dbg
  python-distribute python-distribute-doc doc-base tcpdump tcpreplay wireshark
  graphviz imagemagick python-gnuplot python-pyx ebtables python-visual sox
  xpdf gv hexer librsvg2-bin python-pcapy python-twisted-bin-dbg python-gtk2
  python-glade2 python-qt3 python-wxgtk2.8 python-twisted-runner-dbg
  python2.7-doc binfmt-support mixmaster torbrowser-launcher socat tor-arm
  apparmor-utils obfs4proxy
Recommended packages:
  file python-dumbnet python-pypcap python-pam python-serial logrotate
  tor-geoipdb torsocks
The following NEW packages will be installed:
  geoip-database libevent-2.0-5 libexpat1 libffi6 libgeoip1 libpython-stdlib
  libpython2.7-minimal libpython2.7-stdlib libseccomp2 libssl1.0.0 libyaml-0-2
  mime-support ooniprobe python python-crypto python-geoip python-ipaddr
  python-minimal python-openssl python-parsley python-pkg-resources
  python-pyasn1 python-scapy python-twisted python-twisted-bin
  python-twisted-conch python-twisted-core python-twisted-lore
  python-twisted-mail python-twisted-names python-twisted-news
  python-twisted-runner python-twisted-web python-twisted-words
  python-txsocksx python-txtorcon python-yaml python-zope.interface python2.7
  python2.7-minimal tor
0 upgraded, 41 newly installed, 0 to remove and 0 not upgraded.
Need to get 147 kB/10.5 MB of archives.
After this operation, 47.4 MB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 http://deb.torproject.org/torproject.org/ trusty/main ooniprobe all 1.5.1-2~tpo+ubuntu14.04+1 [147 kB]
Fetched 147 kB in 0s (636 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package libexpat1:amd64.
(Reading database ... 11873 files and directories currently installed.)
Preparing to unpack .../libexpat1_2.1.0-4ubuntu1_amd64.deb ...
Unpacking libexpat1:amd64 (2.1.0-4ubuntu1) ...
Selecting previously unselected package libffi6:amd64.
Preparing to unpack .../libffi6_3.1~rc1+r3.0.13-12_amd64.deb ...
Unpacking libffi6:amd64 (3.1~rc1+r3.0.13-12) ...
Selecting previously unselected package libssl1.0.0:amd64.
Preparing to unpack .../libssl1.0.0_1.0.1f-1ubuntu2_amd64.deb ...
Unpacking libssl1.0.0:amd64 (1.0.1f-1ubuntu2) ...
Selecting previously unselected package libgeoip1:amd64.
Preparing to unpack .../libgeoip1_1.6.0-1_amd64.deb ...
Unpacking libgeoip1:amd64 (1.6.0-1) ...
Selecting previously unselected package libevent-2.0-5:amd64.
Preparing to unpack .../libevent-2.0-5_2.0.21-stable-1ubuntu1_amd64.deb ...
Unpacking libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1) ...
Selecting previously unselected package libseccomp2:amd64.
Preparing to unpack .../libseccomp2_2.1.0+dfsg-1_amd64.deb ...
Unpacking libseccomp2:amd64 (2.1.0+dfsg-1) ...
Selecting previously unselected package libyaml-0-2:amd64.
Preparing to unpack .../libyaml-0-2_0.1.4-3ubuntu3_amd64.deb ...
Unpacking libyaml-0-2:amd64 (0.1.4-3ubuntu3) ...
Selecting previously unselected package libpython2.7-minimal:amd64.
Preparing to unpack .../libpython2.7-minimal_2.7.6-8_amd64.deb ...
Unpacking libpython2.7-minimal:amd64 (2.7.6-8) ...
Selecting previously unselected package python2.7-minimal.
Preparing to unpack .../python2.7-minimal_2.7.6-8_amd64.deb ...
Unpacking python2.7-minimal (2.7.6-8) ...
Selecting previously unselected package mime-support.
Preparing to unpack .../mime-support_3.54ubuntu1_all.deb ...
Unpacking mime-support (3.54ubuntu1) ...
Selecting previously unselected package geoip-database.
Preparing to unpack .../geoip-database_20140313-1_all.deb ...
Unpacking geoip-database (20140313-1) ...
Selecting previously unselected package libpython2.7-stdlib:amd64.
Preparing to unpack .../libpython2.7-stdlib_2.7.6-8_amd64.deb ...
Unpacking libpython2.7-stdlib:amd64 (2.7.6-8) ...
Selecting previously unselected package libpython-stdlib:amd64.
Preparing to unpack .../libpython-stdlib_2.7.5-5ubuntu3_amd64.deb ...
Unpacking libpython-stdlib:amd64 (2.7.5-5ubuntu3) ...
Selecting previously unselected package python2.7.
Preparing to unpack .../python2.7_2.7.6-8_amd64.deb ...
Unpacking python2.7 (2.7.6-8) ...
Selecting previously unselected package python-minimal.
Preparing to unpack .../python-minimal_2.7.5-5ubuntu3_amd64.deb ...
Unpacking python-minimal (2.7.5-5ubuntu3) ...
Selecting previously unselected package python.
Preparing to unpack .../python_2.7.5-5ubuntu3_amd64.deb ...
Unpacking python (2.7.5-5ubuntu3) ...
Selecting previously unselected package python-crypto.
Preparing to unpack .../python-crypto_2.6.1-4build1_amd64.deb ...
Unpacking python-crypto (2.6.1-4build1) ...
Selecting previously unselected package python-geoip.
Preparing to unpack .../python-geoip_1.2.4-2ubuntu5_amd64.deb ...
Unpacking python-geoip (1.2.4-2ubuntu5) ...
Selecting previously unselected package python-ipaddr.
Preparing to unpack .../python-ipaddr_2.1.10-1_all.deb ...
Unpacking python-ipaddr (2.1.10-1) ...
Selecting previously unselected package python-openssl.
Preparing to unpack .../python-openssl_0.13-2ubuntu6_amd64.deb ...
Unpacking python-openssl (0.13-2ubuntu6) ...
Selecting previously unselected package python-pkg-resources.
Preparing to unpack .../python-pkg-resources_3.3-1ubuntu1_all.deb ...
Unpacking python-pkg-resources (3.3-1ubuntu1) ...
Selecting previously unselected package python-pyasn1.
Preparing to unpack .../python-pyasn1_0.1.7-1ubuntu2_all.deb ...
Unpacking python-pyasn1 (0.1.7-1ubuntu2) ...
Selecting previously unselected package python-scapy.
Preparing to unpack .../python-scapy_2.2.0-1_all.deb ...
Unpacking python-scapy (2.2.0-1) ...
Selecting previously unselected package python-twisted-bin.
Preparing to unpack .../python-twisted-bin_13.2.0-1ubuntu1_amd64.deb ...
Unpacking python-twisted-bin (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-zope.interface.
Preparing to unpack .../python-zope.interface_4.0.5-1ubuntu4_amd64.deb ...
Unpacking python-zope.interface (4.0.5-1ubuntu4) ...
Selecting previously unselected package python-twisted-core.
Preparing to unpack .../python-twisted-core_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-core (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-web.
Preparing to unpack .../python-twisted-web_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-web (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-lore.
Preparing to unpack .../python-twisted-lore_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-lore (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-mail.
Preparing to unpack .../python-twisted-mail_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-mail (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-names.
Preparing to unpack .../python-twisted-names_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-names (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-news.
Preparing to unpack .../python-twisted-news_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-news (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-runner.
Preparing to unpack .../python-twisted-runner_13.2.0-1ubuntu1_amd64.deb ...
Unpacking python-twisted-runner (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted-words.
Preparing to unpack .../python-twisted-words_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-words (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-yaml.
Preparing to unpack .../python-yaml_3.10-4build4_amd64.deb ...
Unpacking python-yaml (3.10-4build4) ...
Selecting previously unselected package tor.
Preparing to unpack .../tor_0.2.7.6-1~trusty+1_amd64.deb ...
Unpacking tor (0.2.7.6-1~trusty+1) ...
Selecting previously unselected package python-twisted-conch.
Preparing to unpack .../python-twisted-conch_1%3a13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted-conch (1:13.2.0-1ubuntu1) ...
Selecting previously unselected package python-twisted.
Preparing to unpack .../python-twisted_13.2.0-1ubuntu1_all.deb ...
Unpacking python-twisted (13.2.0-1ubuntu1) ...
Selecting previously unselected package python-parsley.
Preparing to unpack .../python-parsley_1.2-1_all.deb ...
Unpacking python-parsley (1.2-1) ...
Selecting previously unselected package python-txsocksx.
Preparing to unpack .../python-txsocksx_1.13.0.0-1_all.deb ...
Unpacking python-txsocksx (1.13.0.0-1) ...
Selecting previously unselected package python-txtorcon.
Preparing to unpack .../python-txtorcon_0.14.2-1~tpo+ubuntu14.04+1_all.deb ...
Unpacking python-txtorcon (0.14.2-1~tpo+ubuntu14.04+1) ...
Selecting previously unselected package ooniprobe.
Preparing to unpack .../ooniprobe_1.5.1-2~tpo+ubuntu14.04+1_all.deb ...
Unpacking ooniprobe (1.5.1-2~tpo+ubuntu14.04+1) ...
Setting up libexpat1:amd64 (2.1.0-4ubuntu1) ...
Setting up libffi6:amd64 (3.1~rc1+r3.0.13-12) ...
Setting up libssl1.0.0:amd64 (1.0.1f-1ubuntu2) ...
Setting up libgeoip1:amd64 (1.6.0-1) ...
Setting up libevent-2.0-5:amd64 (2.0.21-stable-1ubuntu1) ...
Setting up libseccomp2:amd64 (2.1.0+dfsg-1) ...
Setting up libyaml-0-2:amd64 (0.1.4-3ubuntu3) ...
Setting up libpython2.7-minimal:amd64 (2.7.6-8) ...
Setting up python2.7-minimal (2.7.6-8) ...
Setting up mime-support (3.54ubuntu1) ...
update-alternatives: using /usr/bin/see to provide /usr/bin/view (view) in auto mode
Setting up geoip-database (20140313-1) ...
Setting up libpython2.7-stdlib:amd64 (2.7.6-8) ...
Setting up libpython-stdlib:amd64 (2.7.5-5ubuntu3) ...
Setting up python2.7 (2.7.6-8) ...
Setting up python-minimal (2.7.5-5ubuntu3) ...
Setting up python (2.7.5-5ubuntu3) ...
Setting up python-crypto (2.6.1-4build1) ...
Setting up python-geoip (1.2.4-2ubuntu5) ...
Setting up python-ipaddr (2.1.10-1) ...
Setting up python-openssl (0.13-2ubuntu6) ...
Setting up python-pkg-resources (3.3-1ubuntu1) ...
Setting up python-pyasn1 (0.1.7-1ubuntu2) ...
Setting up python-scapy (2.2.0-1) ...
Setting up python-twisted-bin (13.2.0-1ubuntu1) ...
Setting up python-zope.interface (4.0.5-1ubuntu4) ...
Setting up python-twisted-core (13.2.0-1ubuntu1) ...
Setting up python-twisted-web (13.2.0-1ubuntu1) ...
Setting up python-twisted-lore (13.2.0-1ubuntu1) ...
Setting up python-twisted-mail (13.2.0-1ubuntu1) ...
Setting up python-twisted-names (13.2.0-1ubuntu1) ...
Setting up python-twisted-news (13.2.0-1ubuntu1) ...
Setting up python-twisted-runner (13.2.0-1ubuntu1) ...
Setting up python-twisted-words (13.2.0-1ubuntu1) ...
Setting up python-yaml (3.10-4build4) ...
Setting up tor (0.2.7.6-1~trusty+1) ...
Something or somebody made /var/lib/tor disappear.
Creating one for you again.
Something or somebody made /var/log/tor disappear.
Creating one for you again.
initctl: Unable to connect to Upstart: Failed to connect to socket /com/ubuntu/upstart: Connection refused
invoke-rc.d: policy-rc.d denied execution of start.
Setting up python-twisted-conch (1:13.2.0-1ubuntu1) ...
Setting up python-twisted (13.2.0-1ubuntu1) ...
Setting up python-parsley (1.2-1) ...
Setting up python-txsocksx (1.13.0.0-1) ...
Setting up python-txtorcon (0.14.2-1~tpo+ubuntu14.04+1) ...
Setting up ooniprobe (1.5.1-2~tpo+ubuntu14.04+1) ...
Processing triggers for libc-bin (2.19-0ubuntu6) ...
```

@anadahz: Please give this a go.

**Comment by anadahz** [comment] 2016-06-20 12:34
@irl I experience the same issue with the torproject debian repository enabled.

`# apt-get update && apt-get install ooniprobe`
```
Ign http://nl.archive.ubuntu.com trusty InRelease
Hit http://nl.archive.ubuntu.com trusty Release.gpg                            
Hit http://nl.archive.ubuntu.com trusty Release                                
Hit http://security.ubuntu.com trusty-updates InRelease                        
Hit http://ppa.launchpad.net trusty InRelease                                  
Hit http://nl.archive.ubuntu.com trusty/main amd64 Packages                    
Hit http://nl.archive.ubuntu.com trusty/main Translation-en                    
Ign http://nl.archive.ubuntu.com trusty/main Translation-en_US 
Hit http://security.ubuntu.com trusty-updates/main amd64 Packages              
Hit http://security.ubuntu.com trusty-updates/main Translation-en              
Hit http://ppa.launchpad.net trusty/main amd64 Packages     
Hit http://ppa.launchpad.net trusty/main Translation-en     
Hit http://deb.torproject.org trusty InRelease
Hit http://deb.torproject.org trusty/main amd64 Packages
Ign http://deb.torproject.org trusty/main Translation-en_US
Ign http://deb.torproject.org trusty/main Translation-en
Reading package lists... Done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ooniprobe : Depends: python-txsocksx but it is not installable
             Depends: python-scapy but it is not installable
             Depends: python-txtorcon but it is not going to be installed
             Recommends: python-dumbnet but it is not installable
             Recommends: python-pypcap but it is not installable
E: Unable to correct problems, you have held broken packages.
```

`# cat /etc/apt/sources.list`
```
deb http://nl.archive.ubuntu.com/ubuntu trusty main
deb http://security.ubuntu.com/ubuntu trusty-updates main
deb http://deb.torproject.org/torproject.org trusty main
```

**Comment by hellais** [comment] 2016-06-20 12:45
@anadahz I think you are missing the `universe` repository.

@irl pointed out that this is included by default in ubuntu "Note: In Ubuntu 9.04 (Jaunty) and later, the main, universe, restricted and multiverse repositories are enabled by default.".

He is going to update the README PR to mention this as a note. But I think this is not a bug.

**Comment by anadahz** [comment] 2016-06-20 18:13
I have a default Ubuntu VM, and as it seems it's not having the universe repository included.
I think this should be mentioned in the [installation instructions](https://github.com/TheTorProject/ooni-probe#ooni-in-5-minutes) of ooniprobe as this is what I read to install ooniprobe in Ubuntu.

@hellais I haven't used the the bug tag, let me know how I can better reports such issues in the future.

Ref: https://github.com/TheTorProject/ooni-probe/pull/551

**Comment by irl** [comment] 2016-07-02 23:24
We have now added a note, so I'm closing this one.

@anadahz if there are future issues with the debian/ubuntu packaging, a bug on this repo assigned to me is the best way to do it, I use [bugwarrior](http://bugwarrior.readthedocs.io/en/latest/) and this will automagically appear in my local todo list, make sure you assign it to me though or I may miss it

**Closed by irl** 2016-07-02 23:24 UTC
