### ISSUE TITLE
Failed to download the input file while running complete_no_root.deck or complete.deck

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-probe#486] opened 2016-04-28 20:35 UTC
`# ooniprobe -i data/decks/complete_no_root.deck`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
Log opened.
[D] Checking if backend is present
[D] Checking if file is present
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if backend is present
[D] Checking if file is present
Starting Tor...
[D] Setting control port as 13101
[D] Setting SOCKS port as 11669
Spawning tor process with DataDirectory /tmp/tortmpwYKUuc
5%: Connecting to directory server
10%: Finishing handshake with directory server
15%: Establishing an encrypted directory connection
20%: Asking for networkstatus consensus
25%: Loading networkstatus consensus
40%: Loading authority key certs
45%: Asking for relay descriptors
50%: Loading relay descriptors
51%: Loading relay descriptors
52%: Loading relay descriptors
54%: Loading relay descriptors
56%: Loading relay descriptors
59%: Loading relay descriptors
63%: Loading relay descriptors
68%: Loading relay descriptors
70%: Loading relay descriptors
75%: Loading relay descriptors
80%: Connecting to the Tor network
90%: Establishing a Tor circuit
100%: Done
[D] Building a TorState
Successfully bootstrapped Tor
[D] We now have the following circuits: 
[...]
Found your IP via Tor
Fetching required net test inputs...
[D] Fetching and verifying inputs
[D] Downloading httpo://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
[!] Lookup failed. Retrying.
[!] Lookup failed. Retrying.
[!] Lookup failed. Retrying.
[!] Failed. Giving up.
[!] Failed to download the input file 37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 393, in callback
    self._startRunCallbacks(result)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/oonibclient.py", line 50, in callback
    response.deliverBody(genReceiver(finished, content_length))
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/oonibclient.py", line 95, in genReceiver
    return Downloader(download_path, finished, content_length)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/utils/net.py", line 100, in __init__
    self.fp = open(download_path, 'w+')
exceptions.IOError: [Errno 2] No such file or directory: '/root/.ooni/inputs/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1'
[!] Could not start the director
[!] An unhandled exception occurred while starting the director!
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/deck.py", line 179, in setup
    yield self.fetchAndVerifyNetTestInput(net_test_loader)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "/usr/local/lib/python2.7/dist-packages/ooniprobe-1.4.1-py2.7.egg/ooni/deck.py", line 304, in fetchAndVerifyNetTestInput
    input_file.verify()
exceptions.AttributeError: 'NoneType' object has no attribute 'verify'
Main loop terminated.
```

**Comment by hellais** [comment] 2016-04-28 22:25
This looks like a problem with the deployment of oonibackend. The canonical bouncer is unable to find the input file 37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1.

This can be due to either it not being present in the inputs directory or a misconfigured oonibackend.conf.

**Comment by hellais** [comment] 2016-04-28 22:36
I tried to reproduce this on a fresh install of ooniprobe and can't reproduce. The inputs are downloaded correctly from the canonical collector:

```
Fetching required net test inputs...
[D] Fetching and verifying inputs
[D] Downloading httpo://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
[D] Fetching and verifying inputs
[D] Downloading httpo://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
[D] Downloading httpo://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
```

What version of tor are you running? Can you ensure that you are able to reach the Tor Hidden Service `ihiderha53f36lsd.onion`?

**Comment by anadahz** [comment] 2016-04-28 23:02
`# ooniprobe --version`
```
WARNING: running ooniprobe involves some risk that varies greatly
         from country to country. You should be aware of this when
         running the tool. Read more about this in the manpage or README.
ooniprobe version: 1.4.1
```
It seems that I can't even wget the inputs file:
```
# torsocks wget -v http://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
converted 'http://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1' (ANSI_X3.4-1968) -> 'http://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1' (UTF-8)
--2016-04-28 22:57:11--  http://ihiderha53f36lsd.onion/input/37e60e13536f6afe47a830bfb6b371b5cf65da66d7ad65137344679b24fdccd1
Resolving ihiderha53f36lsd.onion (ihiderha53f36lsd.onion)... 127.42.42.0
Connecting to ihiderha53f36lsd.onion (ihiderha53f36lsd.onion)|127.42.42.0|:80... [Apr 28 22:57:11] ERROR torsocks[1233]: Host unreachable (in socks5_recv_connect_reply() at socks5.c:528)
failed: No route to host.
```
However  I can successfully send reports to the backend, for instance while running:
 `# ooniprobe -i data/decks/fast_no_root.deck`
```
[...]
Found your IP via Tor
Fetching required net test inputs...
[D] Fetching and verifying inputs
[D] Fetching and verifying inputs
Looking up collector and test helpers
Setting collector and test helpers for http_invalid_request_line
Setting collector and test helpers for http_header_field_manipulation
Reporting http://ihiderha53f36lsd.onion/report
[D] Sending {"data_format_version": "0.2.0", "software_name": "ooniprobe", "test_version": "0.2", "software_version": "1.4.1", "test_name": "http_invalid_request_line", "test_start_time": "2016-04-28 23:00:23", "format": "json", "input_hashes": [], "probe_asn": "AS3786", "probe_cc": "KR"}
Creating report with OONIB Reporter. Please be patient.
This may take up to 1-2 minutes...
[D] Creating /tmp/src/ooniprobe/report-http_invalid_request_line-2016-04-28T230023Z.yamloo
[D] Writing report with YAML reporter
[D] Created report with id 20160428T230054Z_AS3786_3Zrw6O24H5Mq6a2qk5Hw7usoS6UPRy4EzPhalltfLTtGSVNFUL
[...]
```

**Comment by hellais** [comment] 2016-05-23 09:12
I guess we have concluded this was an issue with Tor and not ooniprobe. I believe we can close this.

**Closed by hellais** 2016-05-23 09:12 UTC
